# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretty < Formula
  desc "macOS + Linux PTY wrapper that redacts secrets from terminal output"
  homepage "https://github.com/Suryansh-23/secretty"
  version "0.4.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.1/secretty_0.4.1_darwin_amd64.tar.gz"
      sha256 "52b0c684c7d4b5aaf2704fdeaa17e637f6f8a3f8c60af28b29c6dd906d92a6a6"

      def install
        bin.install "secretty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.1/secretty_0.4.1_darwin_arm64.tar.gz"
      sha256 "b737122dfcdc083d09dda4861553e531d1c23983ecc9d16afb9d4eae9bd785df"

      def install
        bin.install "secretty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.1/secretty_0.4.1_linux_amd64.tar.gz"
      sha256 "8768f38a10cd6852f52f995ffbcb58cfc98e5314b6655e4c6d4aa9f5436c0a10"
      def install
        bin.install "secretty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.1/secretty_0.4.1_linux_arm64.tar.gz"
      sha256 "9a8348474aed6c22d21cfe7c747d94949f3aba92fdcea3f450242776fe2c9aa1"
      def install
        bin.install "secretty"
      end
    end
  end

  def caveats
    <<~EOS
      SecreTTY may install shell hooks. Restart your shell to apply changes:
        exec $SHELL -l
      Or reload your shell config:
        source ~/.zshrc
        source ~/.bashrc
        source ~/.config/fish/config.fish
    EOS
  end
end
