# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secretty < Formula
  desc "macOS + Linux PTY wrapper that redacts secrets from terminal output"
  homepage "https://github.com/Suryansh-23/secretty"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.0/secretty_0.4.0_darwin_amd64.tar.gz"
      sha256 "89c5c599b0dee6cdbceb084a1cc14f50a2286a88b69c2130dcf8bd54ed9a5a72"

      def install
        bin.install "secretty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.0/secretty_0.4.0_darwin_arm64.tar.gz"
      sha256 "349dd77b5da621a41d4c5ac12254f18127ffff8c3a6d9ea7ae7e769b97e445a2"

      def install
        bin.install "secretty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.0/secretty_0.4.0_linux_amd64.tar.gz"
      sha256 "a7726a7218eb0113c484d73d3b56e1573addc84b66e4f6f20d895a7aa62d2080"
      def install
        bin.install "secretty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Suryansh-23/secretty/releases/download/v0.4.0/secretty_0.4.0_linux_arm64.tar.gz"
      sha256 "27e7ba94b7102e13c8147293485485d821498fde4220d36c731d8bec8f4d3a40"
      def install
        bin.install "secretty"
      end
    end
  end

  def caveats
    <<~EOS
      SecreTTY may install shell hooks. Restart your shell to apply changes:
        exec $SHELL -l
      Or reload your shell config:
        source ~/.zshrc
        source ~/.bashrc
        source ~/.config/fish/config.fish
    EOS
  end
end
